@server = http://localhost:3000/api
### login
POST {{server}}/users/login

{
  "email": "test@test.com",
  "password": "testtest"
}

### logout
POST {{server}}/users/logout

### register anonymous
POST {{server}}/users/register-anonymous

### register with email
POST {{server}}/users/register-with-email

{
  "email": "@test.com",
  "password": "password123"
}
 
### add email to existing user
POST {{server}}/users/add-email

{
  "email": "test1@test.com",
  "password": "password123",
  "name": "hi"
}

### refresh token
POST {{server}}/users/refresh-token

### info
GET {{server}}/users/me


### change settings
PATCH {{server}}/users/me
# {
#   "password?": "string",
#   "newPassword?":"string",
#   "receivingPaused?": bool,
#   "name?": "string"
# }

{
  "password": "password12",
  "newPassword":"password123",
  "receivingPaused": false,
  "name": "testname"
}

### delete account
DELETE {{server}}/users/me

{
  "password": "testtest"
}

### does user exist
POST {{server}}/users/user-exists

{
  "id": "2WNgb8wY"
}

### send message
POST {{server}}/messages
# {
#   "recipientId": "shortId string", 
#   "text": "string",
#   "replyToMsgId?": "ObjectID string",
#   "allowReply?": bool
# }

{
  "recipientId": "U56Z6gM0", 
  "text": "MESSSSSSSSSSSSSSSAAAAAAAAAAGEEEEEEEEEEEEEEEEE",
  "replyToMsgId": "67bb48c286932c55fcc9d048",
  "allowReply": false
}

### get messages
GET {{server}}/messages
